- name: Create file with required kernel modules
  copy:
    src: ../files/kernel-modules.conf
    dest: /etc/modules-load.d/k8s.conf

- name: iptables required config
  copy:
    src: ../files/iptables.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Sysctl reading of new configs
  command: sysctl --system

- name: Load new modules
  systemd:
    state: restarted
    name: systemd-modules-load.service

- name: Create directory for GPG key
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download GPG key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /tmp/kubernetesgpg

- name: De-armor GPG key
  command: gpg -o /usr/share/keyrings/kubernetes-archive-keyring.gpg --dearmor /tmp/kubernetesgpg

- name: Set up the repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Disable swap from node
  command: swapoff -a
  become: true

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Open Kubenetes API Server, Kubelet API, kube-scheduler, kube-controller-manager and etcd ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: 
      - "6443"
      - "2379"
      - "2380"
      - "10250"
      - "10259"
      - "10257"
      - "6783"
    jump: ACCEPT
    comment: Kubernetes ports

- name: Open CNI (Flannel) UDP ports
  iptables:
    chain: INPUT
    protocol: udp
    destination_ports: 
      - "8285"
      - "8472"
    jump: ACCEPT
    comment: Flannel ports